### ISSUE TITLE
Specify software license

### ISSUE THREAD

**Issue by froseph** [didip/beaker_extensions#20]
Can you please specify a software license for this project? Otherwise, I don't think people can use this software. See Jeff Atwood's post: http://www.codinghorror.com/blog/2007/04/pick-a-license-any-license.html

**Comment by didip** [comment]
I usually prefer MIT, what do you prefer?

**Comment by froseph** [comment]
No preference. MIT works for me :+1:

**Comment by didip** [comment]
ok, i'm swamped with a few different work atm. I'll try to get it done tonight.

**Comment by didip** [comment]
License is added.
