### ISSUE TITLE
Redis keys() raises exeption instead of returning keys

### ISSUE THREAD

**Issue by kxepal** [didip/beaker_extensions#7]
Looks like keys() are implemented, but should it return value in normal way instead of raising generic exception based on it?

https://github.com/didip/beaker_extensions/blob/master/beaker_extensions/redis_.py#L42

``` python
    def keys(self):
        raise self.db_conn.keys('beaker:%s:*' % self.namespace)
```

**Comment by didip** [comment]
Thank you for the report. Fixed in master.
